### PR TITLE
Use https URL in .gitmodules to make it work without github account

### PR DESCRIPTION
**Pull request by srt**
…e.g. in a docker container

### CODE REVIEW

**Comment by srt** [comment]
To run reveal-ck in docker the following two changes are required:
- Use https URL in .gitmodules to make it work without github account and without ssh key and known_hosts entries
- Bind to 0.0.0.0 instead of localhost

**Comment by srt** [comment]
Hmm netstat -ln only shows LISTEN on tcp not on tcp6 so I guess it won't work well on ipv6 only hosts.

**Comment by ginkel** [comment]
Just googled https://github.com/rack/rack/pull/872/files. Seems that supplying nil does the trick.

**Comment by srt** [comment]
nil seems to cause the default value to be used. It only binds to ::1 and 127.0.0.1

**Pull request merged**
